services:
  registry:
    image: registry:2
    ports:
      - 5000:5000
    environment:
      - REGISTRY_LOG_FORMATTER=json
  companion:
    build:
      context: .
      dockerfile: build/package/Dockerfile
    ports:
      - 8081:8080
    environment:
      - REGISTRY_URL=http://registry:5000